#!/usr/bin/env bash
# Installs and configures HAProxy to load-balance web-01 and web-02
apt update
apt-get install -y haproxy

cat > /etc/haproxy/haproxy.cfg << 'EOF'
global
    daemon

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 54.197.0.33:80 check
    server web-02 32.193.226.244:80 check
EOF

service haproxy restart
